// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package retriever

import (
	"github.com/wangle201210/go-rag/server/api/retriever"
)

type ControllerV1 struct{}

func NewV1() retriever.IRetrieverV1 {
	return &ControllerV1{}
}
