// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package knowledge_base

import (
	"github.com/wangle201210/go-rag/server/api/knowledge_base"
	"github.com/wangle201210/go-rag/server/internal/service"
)

type ControllerV1 struct {
	knowledgeBaseService service.IKnowledgeBase
}

func NewV1() knowledge_base.IKnowledgeBaseV1 {
	return &ControllerV1{
		knowledgeBaseService: service.NewKnowledgeBase(),
	}
}
