// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package knowledge_base

import (
	"github.com/wangle201210/go-rag/server/api/knowledge_base"
	knowledge_base2 "github.com/wangle201210/go-rag/server/core/server"
)

type ControllerV1 struct {
	knowledgeBaseService knowledge_base2.IKnowledgeBase
}

func NewV1() knowledge_base.IKnowledgeBaseV1 {
	return &ControllerV1{
		knowledgeBaseService: knowledge_base2.NewKnowledgeBase(),
	}
}
