// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package rag

import (
	"github.com/wangle201210/go-rag/server/api/rag"
)

type ControllerV1 struct{}

func NewV1() rag.IRagV1 {
	return &ControllerV1{}
}
