// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/wangle201210/go-rag/server/internal/dao/internal"
)

// internalKnowledgeBaseDao is an internal type for wrapping the internal DAO implementation.
type internalKnowledgeBaseDao = *internal.KnowledgeBaseDao

// knowledgeBaseDao is the data access object for the table knowledge_base.
// You can define custom methods on it to extend its functionality as needed.
type knowledgeBaseDao struct {
	internalKnowledgeBaseDao
}

var (
	// KnowledgeBase is a globally accessible object for table knowledge_base operations.
	KnowledgeBase = knowledgeBaseDao{
		internal.NewKnowledgeBaseDao(),
	}
)

// Add your custom methods and functionality below.
