// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/wangle201210/go-rag/server/internal/dao/internal"
)

// knowledgeChunksDao is the data access object for the table knowledge_chunks.
// You can define custom methods on it to extend its functionality as needed.
type knowledgeChunksDao struct {
	*internal.KnowledgeChunksDao
}

var (
	// KnowledgeChunks is a globally accessible object for table knowledge_chunks operations.
	KnowledgeChunks = knowledgeChunksDao{internal.NewKnowledgeChunksDao()}
)

// Add your custom methods and functionality below.
