// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/wangle201210/go-rag/server/internal/dao/internal"
)

// knowledgeDocumentsDao is the data access object for the table knowledge_documents.
// You can define custom methods on it to extend its functionality as needed.
type knowledgeDocumentsDao struct {
	*internal.KnowledgeDocumentsDao
}

var (
	// KnowledgeDocuments is a globally accessible object for table knowledge_documents operations.
	KnowledgeDocuments = knowledgeDocumentsDao{internal.NewKnowledgeDocumentsDao()}
)

// Add your custom methods and functionality below.
